name: Reusable Workflow user

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
      - uses: actions/checkout@v2
  docker:
    uses: simplehacker01/Win10/.github/workflows/RDP.yml@main
    with:
      image_name: my-app
    secrets:
      NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
